name: Build and Push to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: ./Pharmacy-Management  # Changed to point to subdirectory
          file: ./Pharmacy-Management/Dockerfile  # Explicit Dockerfile path
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pharmacy-management:latest
          build-args: |
            NODE_ENV=production

      - name: Verify Dockerfile location
        run: ls -la Pharmacy-Management/Dockerfile
